name: Base

on:
  #workflow_dispatch:
  #  inputs:
  #    chinese:
  #      description: 'using chinese apt and pip source mirrors'
  #      default: '0'
  push:
    branches:
      - docker
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWRT repo
        uses: actions/checkout@v2
        with:
          repository: project-openwrt/openwrt
          submodules: true
      - name: Fix premission
        run: docker run -v $PWD:/openwrt elonh/opde:base sudo chown opde:opde -R /openwrt
      - 
        name: debug
        uses: mxschmitt/action-tmate@v2
        if: always()
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - id: var
      #   run: |-
      #     dateDot=$(date +'%y.%m')
      #     echo $dateDot
      #     echo "::set-output name=dateDot::$dateDot"
      # -
      #   name: Build and push scratch
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.scratch
      #     platforms: linux/amd64
      #     build-args: |
      #       CHINESE_APT_MIRRORS=${{ github.event.inputs.chinese }}
      #     push: true
      #     tags: |
      #       elonh/opde:scratch
      #       elonh/opde:scratch-${{steps.var.outputs.dateDot}}
      # -
      #   name: Build and push base
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.base
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       elonh/opde:base
      #       elonh/opde:base-${{steps.var.outputs.dateDot}}
      # -
      #   name: Build and push dev
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.dev
      #     platforms: linux/amd64
      #     build-args: |
      #       CHINESE_PIP_MIRRORS=${{ github.event.inputs.chinese }}
      #     push: true
      #     tags: |
      #       elonh/opde:dev
      #       elonh/opde:dev-${{steps.var.outputs.dateDot}}
