jobs:
  APT:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - id: var
      run: |2

        tag="v$(date + '%Y.%m').${{github.run_number}}"
        echo "::set-output name=date::$(date +'%Y-%m')"
        echo "::set-output name=tag::$tag"
    - uses: actions/cache@v1
      with:
        key: apt-sdk-test-${{steps.time.outputs.date}}-${{ hashFiles('./cache/download-apt.sh')
          }}
        path: ./cache/apt
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |2

        sudo -E apt-get update -y
        sudo -E apt install -y apt-rdepends
        ./scripts/download-apt.sh
        # sudo dpkg -i ./scripts/apt/*.deb
    strategy:
      fail-fast: false
name: Python
'on':
  push:
    branches:
    - python
