name: Docker

on:
  push:
    paths-ignore:
      - '**.md' # ignore *.md files
    branches:
      - docker
    schedule:
      - cron:  '0 0 1 * *' # every month
jobs:
  scratch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Fetch submodule
        run: git submodule update --init --recursive --recommend-shallow
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: var
        run: |-
          dateDot=$(date +'%y.%m')
          echo $dateDot
          echo "::set-output name=dateDot::$dateDot"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.scratch
          platforms: linux/amd64
          push: true
          tags: |
            elonh/opde:scratch
            elonh/opde:scratch-${{steps.var.outputs.dateDot}}
