name: Scratch

on:
  workflow_dispatch:
    inputs:
      chinese:
        description: "using chinese apt and pip source mirrors(Value: 0, 1)"
        required: false
        default: "0"
      subsequent:
        description: "trigger subsequent workflow after build success(Value: 0, 1)"
        required: false
        default: "0"
  schedule:
    - cron: "0 0 1 * *" # every month
jobs:
  scratch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: var
        run: |-
          dateDot=$(date +'%y.%m')
          echo $dateDot
          echo "::set-output name=dateDot::$dateDot"
      - name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64
          build-args: |
            CHINESE_APT_MIRRORS=${{ github.event.inputs.chinese }}
            CHINESE_PIP_MIRRORS=${{ github.event.inputs.chinese }}
          push: true
          tags: |
            elonh/opde:base
          # elonh/opde:base-${{steps.var.outputs.dateDot}}
      - name: Invoke Base workflow
        if: ${{ github.event.inputs.subsequent == '1' || github.event_name == 'schedule'}}
        uses: benc-uk/workflow-dispatch@master
        with:
          workflow: Base
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "subsequent": "1" }'
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "14 days"
          skip-tags: false
