name: Worker

on:
  #workflow_dispatch:
  #  inputs:
  #    chinese:
  #      description: 'using chinese apt and pip source mirrors'
  #      default: '0'
  push:
    branches:
      - docker
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWRT repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: pull docker image
        run: docker pull elonh/opde:worker
      - name: Copy SDK
        run: |
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker sudo chown opde:opde -R /openwrt_bak
          docker run -v $PWD/openwrt:/openwrt_bak elonh/opde:worker rsync -av /openwrt/ /openwrt_bak
      # - name: Create command
      #   run: |
      #     cat>run.sh<<'EOF'
      #     #!/bin/bash
      #     set -e
      #     opde feeds
      #     opde config -i /worker/05.worker.conf
      #     cat .opde/min-config.in
      #     opde download
      #     opde build
      #     EOF
      - name: Opde feeds
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde feeds
      - name: Opde config
        run: |
          docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde config /worker/01.worker.conf
          cat .opde/min-config.in
      - name: Opde download
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde download
      - name: Opde build
        run: docker run -v $PWD/openwrt:/openwrt elonh/opde:worker opde build
      - name: Fix premission
        run: sudo chown $(id -u -n):$(id -g -n) -R openwrt

      - uses: actions/upload-artifact@v2
        with:
          name: Packages-01
          path: ./openwrt/bin
      - uses: actions/upload-artifact@v2
        with:
          name: Log-01
          path: ./openwrt/.opde
      # - 
        # name: debug # docker run -it -v $PWD:/openwrt elonh/opde:base bash
        # uses: mxschmitt/action-tmate@v2
        # if: always()
