name: Worker

on:
  #workflow_dispatch:
  #  inputs:
  #    chinese:
  #      description: 'using chinese apt and pip source mirrors'
  #      default: '0'
  push:
    branches:
      - docker
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWRT repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: pull docker image
        run: docker pull elonh/opde:worker
      - run: mkdir openwrt openwrt/dl openwrt/logs openwrt/bin openwrt/database -p
      - name: Fix premission
        run: docker run -v $PWD/openwrt/bin:/openwrt/bin -v $PWD/openwrt/logs:/openwrt/logs elonh/opde:worker sudo chown opde:opde -R /openwrt/bin /openwrt/logs
      - name: Create command
        run: |
          cat>run.sh<<'EOF'
          #!/bin/bash
          set -e
          opde feeds
          opde config -i /worker/05.worker.conf
          cat .opde/min-config.in
          opde download
          opde build
          EOF
      - name: Run in Docker
        run: docker run -v $PWD/openwrt/bin:/openwrt/bin -v $PWD/openwrt/logs:/openwrt/logs -v $PWD/run.sh:/run.sh elonh/opde:worker bash /run.sh
      - name: Fix premission
        run: sudo chown $(id -u -n):$(id -g -n) -R dl logs bin .opde
        working-directory: openwrt
      - 
        name: debug # docker run -it -v $PWD:/openwrt elonh/opde:base bash
        uses: mxschmitt/action-tmate@v2
        if: always()
